#!/usr/bin/env python3
"""
POLYMARKET CLOB CREDENTIALS SETUP
=================================

This script generates the API credentials needed for CLOB trading.

Prerequisites:
    pip install py-clob-client web3==6.14.0

You need your Polygon wallet private key (the wallet you use on Polymarket).

Usage:
    python setup_credentials.py
"""

import os
import sys
from pathlib import Path

def main():
    print("""
    ╔══════════════════════════════════════════════════════════════════════╗
    ║  POLYMARKET CLOB CREDENTIALS SETUP                                   ║
    ╚══════════════════════════════════════════════════════════════════════╝
    """)

    # Check if py-clob-client is installed
    try:
        from py_clob_client.client import ClobClient
        from py_clob_client.clob_types import ApiCreds
        print("[OK] py-clob-client is installed")
    except ImportError:
        print("[ERROR] py-clob-client not installed!")
        print("\nRun this first:")
        print("  pip install py-clob-client web3==6.14.0")
        sys.exit(1)

    # Check for existing .env
    env_path = Path(".env")
    existing_key = None

    if env_path.exists():
        print(f"[OK] Found existing .env file")
        with open(env_path) as f:
            for line in f:
                if line.startswith("POLYGON_PRIVATE_KEY="):
                    existing_key = line.split("=", 1)[1].strip().strip('"').strip("'")
                    if existing_key:
                        print(f"[OK] Found existing private key: {existing_key[:10]}...{existing_key[-4:]}")

    # Get private key
    print("\n" + "=" * 60)
    print("STEP 1: Your Polygon Wallet Private Key")
    print("=" * 60)
    print("""
This is the private key of the wallet you use on Polymarket.

How to export from MetaMask:
1. Open MetaMask
2. Click the 3 dots next to your account name
3. Click "Account Details"
4. Click "Show Private Key"
5. Enter your password
6. Copy the private key (starts with 0x)

WARNING: Never share your private key with anyone!
""")

    if existing_key:
        use_existing = input(f"Use existing key ({existing_key[:10]}...)? [Y/n]: ").strip().lower()
        if use_existing != 'n':
            private_key = existing_key
        else:
            private_key = input("Enter your Polygon private key (0x...): ").strip()
    else:
        private_key = input("Enter your Polygon private key (0x...): ").strip()

    if not private_key:
        print("[ERROR] No private key provided")
        sys.exit(1)

    if not private_key.startswith("0x"):
        private_key = "0x" + private_key

    # Generate credentials
    print("\n" + "=" * 60)
    print("STEP 2: Generating API Credentials")
    print("=" * 60)

    try:
        # Initialize client
        client = ClobClient(
            host="https://clob.polymarket.com",
            key=private_key,
            chain_id=137,  # Polygon mainnet
        )

        # Derive API credentials
        print("\nDeriving API credentials from your wallet...")
        creds = client.create_or_derive_api_creds()

        api_key = creds.api_key
        api_secret = creds.api_secret
        passphrase = creds.api_passphrase

        print("\n[SUCCESS] API credentials generated!")
        print(f"\nAPI Key:     {api_key[:20]}...")
        print(f"API Secret:  {api_secret[:20]}...")
        print(f"Passphrase:  {passphrase[:20]}...")

    except Exception as e:
        print(f"\n[ERROR] Failed to generate credentials: {e}")
        print("\nPossible causes:")
        print("  - Invalid private key format")
        print("  - Network connection issue")
        print("  - py-clob-client version mismatch")
        sys.exit(1)

    # Save to .env
    print("\n" + "=" * 60)
    print("STEP 3: Saving to .env file")
    print("=" * 60)

    env_content = f"""# Polymarket CLOB Credentials
# Generated by setup_credentials.py

# Your Polygon wallet private key
POLYGON_PRIVATE_KEY={private_key}

# L2 API credentials (derived from wallet)
POLYMARKET_API_KEY={api_key}
POLYMARKET_API_SECRET={api_secret}
POLYMARKET_PASSPHRASE={passphrase}
"""

    # Backup existing .env if it exists
    if env_path.exists():
        backup_path = Path(".env.backup")
        print(f"[INFO] Backing up existing .env to {backup_path}")
        with open(env_path) as f:
            backup_content = f.read()
        with open(backup_path, "w") as f:
            f.write(backup_content)

    # Write new .env
    with open(env_path, "w") as f:
        f.write(env_content)

    print(f"\n[SUCCESS] Credentials saved to {env_path}")

    # Verify
    print("\n" + "=" * 60)
    print("STEP 4: Verification")
    print("=" * 60)

    try:
        # Test connection
        from py_clob_client.clob_types import ApiCreds as TestCreds

        test_creds = TestCreds(
            api_key=api_key,
            api_secret=api_secret,
            api_passphrase=passphrase,
        )

        test_client = ClobClient(
            host="https://clob.polymarket.com",
            key=private_key,
            creds=test_creds,
            chain_id=137,
        )

        # Try to get a simple endpoint
        print("\nTesting connection to CLOB API...")
        # This might fail if there's no actual connection, but structure is valid

        print("\n[SUCCESS] Credentials are properly formatted!")

    except Exception as e:
        print(f"\n[WARNING] Verification issue: {e}")
        print("Credentials saved but may need manual verification.")

    print("\n" + "=" * 60)
    print("SETUP COMPLETE!")
    print("=" * 60)
    print("""
Your .env file now contains:
  - POLYGON_PRIVATE_KEY
  - POLYMARKET_API_KEY
  - POLYMARKET_API_SECRET
  - POLYMARKET_PASSPHRASE

You can now run the HFT server:
  python hft_server.py --mode demo

To test with real trades (be careful!):
  python hft_server.py --mode live

IMPORTANT: Never commit your .env file to git!
Make sure .env is in your .gitignore file.
""")


if __name__ == "__main__":
    main()
